image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      pip install virtualenv
      python -m virtualenv --system-site-packages .venv
      source .venv/bin/activate
      pip install -r ./requirements.txt
