ANIME_SKETCH_COLORIZATION_DATASET_KAGGLE_ID = 'ktaebum'
ANIME_SKETCH_COLORIZATION_DATASET_DATASET_ID = 'anime-sketch-colorization-pair'

ANIME_SKETCH_COLORIZATION_COLORGRAM_SCOPE = 'colorgram'
ANIME_SKETCH_COLORIZATION_TRAIN_SCOPE = 'train'
ANIME_SKETCH_COLORIZATION_VAL_SCOPE = 'val'
ANIME_SKETCH_COLORIZATION_DATA_SCOPE = 'data'
